-- DDL - Prueba técnica KAWAK
-- Base de datos: kawak_docs
-- Charset/Collation: UTF-8 (utf8mb4)

CREATE DATABASE IF NOT EXISTS kawak_docs
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE kawak_docs;

CREATE TABLE IF NOT EXISTS PRO_PROCESO (
  PRO_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRO_NOMBRE VARCHAR(100) NOT NULL,
  PRO_PREFIJO VARCHAR(10) NOT NULL,
  PRIMARY KEY (PRO_ID),
  UNIQUE KEY UK_PRO_PREFIJO (PRO_PREFIJO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS TIP_TIPO_DOC (
  TIP_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  TIP_NOMBRE VARCHAR(100) NOT NULL,
  TIP_PREFIJO VARCHAR(10) NOT NULL,
  PRIMARY KEY (TIP_ID),
  UNIQUE KEY UK_TIP_PREFIJO (TIP_PREFIJO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS DOC_DOCUMENTO (
  DOC_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  DOC_NOMBRE VARCHAR(255) NOT NULL,
  DOC_CODIGO VARCHAR(50) NOT NULL,
  DOC_CONSECUTIVO INT UNSIGNED NOT NULL,
  DOC_CONTENIDO LONGTEXT NULL,
  DOC_ID_TIPO INT UNSIGNED NOT NULL,
  DOC_ID_PROCESO INT UNSIGNED NOT NULL,
  PRIMARY KEY (DOC_ID),
  UNIQUE KEY UK_DOC_CODIGO (DOC_CODIGO),
  UNIQUE KEY UK_DOC_TIPO_PROCESO_CONSEC (DOC_ID_TIPO, DOC_ID_PROCESO, DOC_CONSECUTIVO),
  KEY IDX_DOC_NOMBRE (DOC_NOMBRE),
  KEY IDX_DOC_TIPO (DOC_ID_TIPO),
  KEY IDX_DOC_PROCESO (DOC_ID_PROCESO),
  CONSTRAINT FK_DOC_TIPO FOREIGN KEY (DOC_ID_TIPO) REFERENCES TIP_TIPO_DOC (TIP_ID),
  CONSTRAINT FK_DOC_PROCESO FOREIGN KEY (DOC_ID_PROCESO) REFERENCES PRO_PROCESO (PRO_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

